apiVersion: v1
kind: ConfigMap
metadata:
  name: drill-config
data:
  API_HOST: "drill-admin-cluster-ip.default.svc.cluster.local"
  POSTGRES_DB_HOST: "my-postgres-postgresql.default.svc.cluster.local"
  POSTGRES_DB: "postgres"
  DRILL_ADMIN_BACKEND_DB_MAX_POOL_SIZE: "50"
  DRILL_UI_BASE_URL: "http://localhost:8095"
  # TODO move to secrets
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "mysecretpassword"
