postgresqlVersion: 17
global:
  postgresql:
    auth:
      postgresPassword: mysecretpassword
      database: postgres

primary:
  initContainers:
    - name: init-migration-files
      image: alpine:3.15
      command: ["sh", "-c"]
      args:
        - wget -O /docker-entrypoint-initdb.d/data.sql https://github.com/Drill4J/drill-metabase-dashboards/releases/download/v20/data.sql
      volumeMounts:
        - name: migration-volume
          mountPath: /docker-entrypoint-initdb.d

  extraVolumeMounts:
    - name: migration-volume
      mountPath: /docker-entrypoint-initdb.d

  extraVolumes:
    - name: migration-volume
      emptyDir: {}
