apiVersion: apps/v1
kind: Deployment
metadata:
  name: drill-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drill-ui
  template:
    metadata:
      labels:
        app: drill-ui
    spec:
      containers:
        - name: drill-ui
          image: ghcr.io/drill4j/drill4j-ui:0.1.1
          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: API_HOST
            - name: API_PORT
              value: "8090"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: drill-ui
spec:
  type: NodePort
  selector:
    app: drill-ui
  ports:
    - port: 8091        # Expose port 8091 externally on the node
      targetPort: 8080   # Forward traffic to port 8080 inside the container
      nodePort: 30091    # Expose port 30091 externally (can be any valid port between 30000-32767)