apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.ui.name | default "ui" }}
  labels:
    app: ui
spec:
  replicas: {{ .Values.deployments.ui.replicaCount }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: {{ .Values.deployments.ui.containerName | default "ui" }}
          image: {{ .Values.deployments.ui.image.repository }}:{{ .Values.deployments.ui.image.tag }}
          env:
            - name: API_HOST
              value: {{ .Values.config.API_HOST }}
            - name: API_PORT
              value: "8090"
            - name: BASE_PATH
              value: "/ui"
          ports:
            - containerPort: {{ .Values.deployments.ui.service.targetPort }}
