apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.admin.name | default "admin" }}
  labels:
    app: admin
spec:
  replicas: {{ .Values.deployments.admin.replicaCount }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: {{ .Values.deployments.admin.name | default "admin" }}
          image: {{ .Values.deployments.admin.image.repository }}:{{ .Values.deployments.admin.image.tag }}
          env:
            {{- range .Values.deployments.admin.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.deployments.admin.service.targetPort }}
