{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dbSecret }}
type: Opaque
data:
  {{ .Values.secrets.dbUsernameKey }}: {{ .Values.secrets.dbUsername | b64enc | quote }}
  {{ .Values.secrets.dbPasswordKey }}: {{ .Values.secrets.dbPassword | b64enc | quote }}
{{- end }}
