apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.admin.service.name | default "admin" }}
spec:
  type: {{ .Values.deployments.admin.service.type | default "ClusterIP" }}
  selector:
    app: admin
  ports:
    - port: {{ .Values.deployments.admin.service.port }}
      targetPort: {{ .Values.deployments.admin.service.targetPort }}
