apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.drill-admin.service.name | default "drill-admin" }}
spec:
  type: {{ .Values.deployments.drill-admin.service.type | default "ClusterIP" }}
  selector:
    app: drill-admin
  ports:
    - port: {{ .Values.deployments.drill-admin.service.port }}
      targetPort: {{ .Values.deployments.drill-admin.service.targetPort }}
