apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ghcr.io/drill4j/admin:0.9.10
          env:
            - name: DRILL_METRICS_UI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: DRILL_UI_BASE_URL
            - name: DRILL_DB_PORT
              value: "5432"
            - name: DRILL_AGENTS_SOCKET_TIMEOUT
              value: "6000"

            - name: DRILL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: POSTGRES_DB_HOST
                  
            - name: DRILL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: POSTGRES_DB
            - name: DRILL_DB_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: POSTGRES_USER
            - name: DRILL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: POSTGRES_PASSWORD
            - name: DRILL_DB_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: DRILL_ADMIN_BACKEND_DB_MAX_POOL_SIZE
            - name: DRILL_SCHEDULER_REFRESH_VIEWS_INTERVAL_IN_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: DRILL_SCHEDULER_REFRESH_VIEWS_INTERVAL_IN_MINUTES
            - name: LOG_LEVEL
              value: "info"
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30

---

apiVersion: v1
kind: Service
metadata:
  name: admin-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - port: 8090
      targetPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: admin-node-port
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - port: 8090
      targetPort: 8090
