apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      initContainers:
        - name: init-metabase
          image: ghcr.io/drill4j/drill-metabase-dashboards:0.9.2
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: db-metabase
      containers:
        - name: metabase
          image: metabase/metabase@sha256:96416c11371d400aecc2073b8d0e8335cc7c413b236ef724e51dda095b2580ea
          env:
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: POSTGRES_DB_HOST
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              value: postgres
            - name: MB_DB_PASS
              value: mysecretpassword
            - name: MB_DB_DBNAME
              value: db-metabase
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  type: NodePort
  selector:
    app: metabase
  ports:
    - port: 8095
      targetPort: 3000
