apiVersion: v1
kind: Namespace
metadata:
  name: realworld

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-api
  namespace: realworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworld-api
  template:
    metadata:
      labels:
        app: realworld-api
    spec:
      initContainers:
        - name: init-file-downloader
          image: alpine
          command:
            - sh
            - -c
            - |
              apk add --no-cache wget unzip && \
              wget -O /data/agent.zip https://github.com/Drill4J/java-agent/releases/download/v0.9.6/agent-linuxX64-0.9.6.zip && \
              unzip -o /data/agent.zip -d /data && \
              mv /data/linuxX64-0.9.6 /data/agent && \
              ls /data/agent && \
              echo "Download and extraction complete"
          volumeMounts:
            - name: agent-files
              mountPath: /data
      containers:
        - name: realworld-api
          image: drill4j/real-world-spring-api:java-and-js-coverage-0.1.0
          ports:
            - containerPort: 9001
          env:
            - name: ACCESS_CONTROL_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: realworld-config
                  key: ACCESS_CONTROL_ALLOW_ORIGIN
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: realworld-config
                  key: JAVA_TOOL_OPTIONS
            - name: DRILL_API_URL
              valueFrom:
                configMapKeyRef:
                  name: realworld-config
                  key: DRILL_ADMIN_ADDRESS
            - name: DRILL_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: realworld-config
                  key: DRILL_API_KEY
            - name: DRILL_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: realworld-config
                  key: DRILL_APP_ID
            - name: DRILL_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: realworld-config
                  key: DRILL_GROUP_ID
            - name: DRILL_BUILD_VERSION
              value: "0.1.0"
            - name: DRILL_PACKAGE_PREFIXES
              value: "io/spring"
            - name: DRILL_ENV_ID
              value: "demo-1"
          args: ["java", "-jar", "/spring-boot-realworld-example-app-0.0.1-SNAPSHOT.jar"]
          volumeMounts:
            - name: agent-files
              mountPath: /data
      volumes:
        - name: agent-files
          emptyDir: {}

---

# realworld-api Service
apiVersion: v1
kind: Service
metadata:
  name: realworld-api
  namespace: realworld
spec:
  type: NodePort
  selector:
    app: realworld-api
  ports:
    - port: 9001
      targetPort: 9001

---

# ConfigMap for Environment Variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: realworld-config
  namespace: realworld
data:
  ACCESS_CONTROL_ALLOW_ORIGIN: "*"
  JAVA_TOOL_OPTIONS: "-agentpath:/data/agent/libdrill_agent.so"
  DRILL_ADMIN_ADDRESS: "http://drill-admin-cluster-ip.default.svc.cluster.local:8090/api"
  DRILL_API_KEY: "1_33b7bad7f3cf719db2f99be59dfa34f9123d942e7018294d65196d68a0877eed"
  DRILL_APP_ID: "backend"
  DRILL_GROUP_ID: "realworld"
