apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/drill4j/drill4j-ui:0.1.2
          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: drill-config
                  key: API_HOST
            - name: API_PORT
              value: "8090"
            - name: BASE_PATH
              value: "/ui"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - port: 8091        # Expose port 8091 externally on the node
      targetPort: 8080   # Forward traffic to port 8080 inside the container