apiVersion: apps/v1
kind: Deployment
metadata:
  name: drill-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drill-admin
  template:
    metadata:
      labels:
        app: drill-admin
    spec:
      containers:
        - name: drill-admin
          image: ghcr.io/drill4j/admin:${DRILL_ADMIN_BACKEND_VERSION}
          env:
            - name: DRILL_METRICS_UI_BASE_URL
              value: "${DRILL_UI_BASE_URL}"
            - name: DRILL_DB_PORT
              value: "5432"
            - name: DRILL_AGENTS_SOCKET_TIMEOUT
              value: "6000"
            - name: DRILL_DB_HOST
              value: "postgres"
            - name: DRILL_DB_NAME
              value: "${POSTGRES_DB}"
            - name: DRILL_DB_USER_NAME
              value: "${POSTGRES_USER}"
            - name: DRILL_DB_PASSWORD
              value: "${POSTGRES_PASSWORD}"
            - name: DRILL_DB_MAX_POOL_SIZE
              value: "${DRILL_ADMIN_BACKEND_DB_MAX_POOL_SIZE}"
            - name: LOG_LEVEL
              value: "info"
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30