apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  ports:
    - port: 8095
      targetPort: 3000
  selector:
    app: metabase
  type: NodePort  # Change to LoadBalancer if using cloud provider
