config:
  API_HOST: "admin.default.svc.cluster.local"
  DRILL_UI_BASE_URL: "http://localhost:8095"

deployments:
  admin:
    name: admin
    replicaCount: 1
    image:
      repository: ghcr.io/drill4j/admin
      tag: "0.9.11"
    env:
      - name: DRILL_DB_HOST
        value: "drill-postgresql"
      - name: DRILL_DB_PORT
        value: "5432"
      - name: DRILL_DB_NAME
        value: "db-drill"
      - name: DRILL_DB_MAX_POOL_SIZE
        value: "50"
      - name: DRILL_METRICS_UI_BASE_URL
        value: "http://localhost:8095"
      - name: DRILL_SCHEDULER_REFRESH_VIEWS_INTERVAL_IN_MINUTES
        value: "1"
      - name: LOG_LEVEL
        value: "info"
    service:
      name: admin
      type: ClusterIP
      port: 8090
      targetPort: 8090

  ui:
    name: ui
    replicaCount: 1
    image:
      repository: ghcr.io/drill4j/drill4j-ui
      tag: "0.1.2"
    env:
      - name: API_HOST
        value: "admin.default.svc.cluster.local"
      - name: API_PORT
        value: "8090"
      - name: BASE_PATH
        value: "/ui"
    service:
      name: ui
      type: NodePort
      port: 8091
      targetPort: 8080

  metabase:
    name: metabase
    replicaCount: 1
    initContainer:
      image: ghcr.io/drill4j/drill-metabase-dashboards
      tag: "0.9.3"
      env:
        - name: POSTGRES_HOST
          value: "drill-postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "db-metabase"
    image:
      repository: metabase/metabase
      tag: "v0.53.7.x"
    env:
      - name: MB_DB_TYPE
        value: "postgres"
      - name: MB_DB_HOST
        value: "drill-postgresql"
      - name: MB_DB_PORT
        value: "5432"
      - name: MB_DB_DBNAME
        value: "db-metabase"
    service:
      name: metabase
      type: NodePort
      port: 8095
      targetPort: 3000
    probes:
      liveness:
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 5

ingress:
  name: app-ingress
  paths:
    ui:
      path: /ui(/|$)(.*)
      service:
        name: ui
        port: 8091
    admin:
      path: /admin(/|$)(.*)
      service:
        name: admin
        port: 8090
    metabase:
      path: /metabase(/|$)(.*)
      service:
        name: metabase
        port: 8095

secrets:
  dbSecret: "drill-db-secrets"  # Default secret name (can be overridden)
  create: false  # Helm will NOT create a secret by default (secure)
  dbUsernameKey: "db-username"
  dbPasswordKey: "db-password"
  dbUsername: "postgres"  # Used only if `create: true`
  dbPassword: "12345"  # Used only if `create: true`

postgresql:
  auth:
    existingSecret: "drill-db-secrets"
    secretKeys:
      adminPasswordKey: "db-password"	
      userPasswordKey: "db-password"	
    database: "db-drill"
  
  primary:
    persistence:
      enabled: true
      size: 20Gi

    persistentVolumeClaimRetentionPolicy:
      enabled: true
  
  shmVolume:
    enabled: true
    sizeLimit: 1Gi # TODO does not work